### ISSUE TITLE
Collapsible map legend element

### ISSUE THREAD

**Issue by IndigoWizard** [IndigoWizard/wildfire-burn-severity#2]
#### _please make a PR to the dev branch where it would be merged if approved._

Implementing a collapsible map legend.
The current branca element based legend is just draggable but not collapsible, it would be great to implement such a feature to minimize the space it takes up on while navigating the map.

Make sure the legend stays draggable when implementing the collapse feature.

https://user-images.githubusercontent.com/43890965/197423021-20ac629f-e65d-445f-ada4-a350f73da816.mp4

### Info
The project is using Folium and earthengine-api to generate the map and the raster/vector layers. By default, Folium creates a map in a separate HTML file [wildfire-burn-severity/webmap.html](https://github.com/IndigoWizard/wildfire-burn-severity/blob/main/webmap.html) from the main python app [wildfire-burn-severity/webmap.py](https://github.com/IndigoWizard/wildfire-burn-severity/blob/main/webmap.py) .

Even though the project is python based, it generates Leaflet.js based maps through the output html file, the legend is pure HTML/CSS/JS that can be injected in the main python source using [Branca library](https://github.com/python-visualization/branca).

I put the branca element based legend in a separate python file [wildfire-burn-severity/uilegend.py](https://github.com/IndigoWizard/wildfire-burn-severity/blob/main/uilegend.py). You can extract it and treat as just HTML so you get an easier time coding and seeing the results locally as in opposite to running the python app which requires a validated Google Earth Engine account (_it takes long time to be accepted and validated_).

The css is of course in the [src/css](https://github.com/IndigoWizard/wildfire-burn-severity/blob/main/src/ui.css)

### NOTE:
Make sure you put a preview (gif/mp4) of your result in the Pull Request so I can check what it looks like and how it behaves.

**Comment by sfrunza13** [comment]
Hello, can I try working on this?

**Comment by IndigoWizard** [comment]
@sfrunza13 I asigned you the issue to work on.
Something comes up to mind, when it comes to testing:
If you want to test your code and don't have the _google earth engine account_, you can past the new code in the [webmap.html](https://github.com/IndigoWizard/wildfire-burn-severity/blob/dev/webmap.html) thus replacing code from [Line 41](https://github.com/IndigoWizard/wildfire-burn-severity/blob/ed6a2f737b9a446be0f18c616c71a890d995ae3e/webmap.html#L41) to [Line 137](https://github.com/IndigoWizard/wildfire-burn-severity/blob/ed6a2f737b9a446be0f18c616c71a890d995ae3e/webmap.html#L137) .

PS:
_[webmap.html](https://github.com/IndigoWizard/wildfire-burn-severity/blob/dev/webmap.html)_ file is rewritten every time the python script is run, thus calling the html code from _[uilegend.py](https://github.com/IndigoWizard/wildfire-burn-severity/blob/dev/uilegend.py)_ into webmap.py using branca. That's why it's just used for testing when you don't have a gee account.

**Comment by IndigoWizard** [comment]
@sfrunza13 Looks great!

**Comment by IndigoWizard** [comment]
@sfrunza13 there are other repos here that are up for hacktoberfest if interested or you can check https://github.com/House-of-M for more.
Thanks for your contribution!
